from langchain_core.tools import tool
from typing import Annotated, Optional
from tradingagents.dataflows.postgresql_data import (
    get_fundamentals_postgresql,
    get_balance_sheet_postgresql,
    get_income_statement_postgresql,
    get_cashflow_postgresql
)


@tool
def get_fundamentals(
    ticker: Annotated[str, "ticker symbol"],
    curr_date: Annotated[str, "current date you are trading at, yyyy-mm-dd"],
) -> str:
    """
    Retrieve comprehensive fundamental data for a given ticker symbol from PostgreSQL database.
    Data is sourced only from verified sources: NSE, BSE, or SEBI.
    All financial numbers come directly from the database - never generated by the LLM.
    Args:
        ticker (str): Ticker symbol of the company (dynamically provided)
        curr_date (str): Current date you are trading at, yyyy-mm-dd
    Returns:
        str: A formatted report containing comprehensive fundamental data with source attribution and as-of dates
    """
    return get_fundamentals_postgresql(ticker=ticker.upper(), curr_date=curr_date)


@tool
def get_balance_sheet(
    ticker: Annotated[str, "ticker symbol"],
    freq: Annotated[str, "reporting frequency: annual/quarterly"] = "quarterly",
    curr_date: Annotated[Optional[str], "current date you are trading at, yyyy-mm-dd"] = None,
) -> str:
    """
    Retrieve balance sheet data for a given ticker symbol from PostgreSQL database.
    Data is sourced only from verified sources: NSE, BSE, or SEBI.
    All financial numbers come directly from the database - never generated by the LLM.
    Args:
        ticker (str): Ticker symbol of the company (dynamically provided)
        freq (str): Reporting frequency: annual/quarterly (default quarterly)
        curr_date (str): Current date you are trading at, yyyy-mm-dd (optional)
    Returns:
        str: A formatted report containing balance sheet data with source attribution and as-of dates
    """
    return get_balance_sheet_postgresql(ticker=ticker.upper(), freq=freq, curr_date=curr_date)


@tool
def get_cashflow(
    ticker: Annotated[str, "ticker symbol"],
    freq: Annotated[str, "reporting frequency: annual/quarterly"] = "quarterly",
    curr_date: Annotated[Optional[str], "current date you are trading at, yyyy-mm-dd"] = None,
) -> str:
    """
    Retrieve cash flow statement data for a given ticker symbol from PostgreSQL database.
    Data is sourced only from verified sources: NSE, BSE, or SEBI.
    All financial numbers come directly from the database - never generated by the LLM.
    Args:
        ticker (str): Ticker symbol of the company (dynamically provided)
        freq (str): Reporting frequency: annual/quarterly (default quarterly)
        curr_date (str): Current date you are trading at, yyyy-mm-dd (optional)
    Returns:
        str: A formatted report containing cash flow statement data with source attribution and as-of dates
    """
    return get_cashflow_postgresql(ticker=ticker.upper(), freq=freq, curr_date=curr_date)


@tool
def get_income_statement(
    ticker: Annotated[str, "ticker symbol"],
    freq: Annotated[str, "reporting frequency: annual/quarterly"] = "quarterly",
    curr_date: Annotated[Optional[str], "current date you are trading at, yyyy-mm-dd"] = None,
) -> str:
    """
    Retrieve income statement data for a given ticker symbol from PostgreSQL database.
    Data is sourced only from verified sources: NSE, BSE, or SEBI.
    All financial numbers come directly from the database - never generated by the LLM.
    Args:
        ticker (str): Ticker symbol of the company (dynamically provided)
        freq (str): Reporting frequency: annual/quarterly (default quarterly)
        curr_date (str): Current date you are trading at, yyyy-mm-dd (optional)
    Returns:
        str: A formatted report containing income statement data with source attribution and as-of dates
    """
    return get_income_statement_postgresql(ticker=ticker.upper(), freq=freq, curr_date=curr_date)